[project]
name = "fastapi-orderly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "J2mF", email = "mp4-12cs5@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "argon2-cffi>=25.1.0",
    "fastapi[standard]>=0.141.1",
    "psycopg>=3.3.6",
    "pydantic-settings>=2.15.0",
    "pyseto>=1.10.0",
    "sqlalchemy[asyncio]>=2.0.54",
    "uuid6>=2025.0.1",
    "uvicorn[standard]>=0.52.4",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "debugpy>=1.8.22",
    "httpx>=0.28.1",
    "ipython>=9.17.1",
    "jedi>=0.20.0",
    "mypy>=2.3.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.7",
    "ty>=0.0.80",
]

[tool.ruff]
line-length = 100
target-version = "py313"
lint.select = ["E", "F", "W", "I", "N", "UP", "B", "SIM", "RUF", "ANN"]
lint.ignore = []
format.quote-style = "double"
format.indent-style = "space"

[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
    # Allow Pydantic's `@validator` decorator to trigger class method treatment.
    "pydantic.validator",
    # Allow SQLAlchemy's dynamic decorators, like `@field.expression`, to trigger class method treatment.
    "declared_attr",
    "declared_attr.directive",
    "sqlalchemy.orm.declared_attr",
    "sqlalchemy.orm.declared_attr.directive",
    "expression",
    "comparator",
]

[tool.mypy]
strict = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
addopts = "--cov=fastapi_orderly --cov-report=term-missing"

[tool.typos.files]
extend-exclude = [
    "src/fastapi_orderly/core/db/alembic/versions/**",
]
