"""refresh token

Revision ID: b6f8d8feea14
Revises: 3ff4cb2c9bf6
Create Date: 2026-10-05 12:34:47.930696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6f8d8feea14"
down_revision: str | Sequence[str] | None = "3ff4cb2c9bf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("refresh_token", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_refresh_token_user_id"), "refresh_token", ["user_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_refresh_token_user_id_user_account"),
        "refresh_token",
        "user_account",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_refresh_token_user_id_user_account"), "refresh_token", type_="foreignkey"
    )
    op.drop_index(op.f("ix_refresh_token_user_id"), table_name="refresh_token")
    op.drop_column("refresh_token", "user_id")
    # ### end Alembic commands ###
